// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: builtin.proto

package builtinpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Builtin_Ping_FullMethodName = "/builtin.Builtin/Ping"
)

// BuiltinClient is the client API for Builtin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Builtin 是 builtin 领域的 gRPC 服务, 与 REST 侧 /api/v1/ping 对应.
type BuiltinClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type builtinClient struct {
	cc grpc.ClientConnInterface
}

func NewBuiltinClient(cc grpc.ClientConnInterface) BuiltinClient {
	return &builtinClient{cc}
}

func (c *builtinClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Builtin_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuiltinServer is the server API for Builtin service.
// All implementations must embed UnimplementedBuiltinServer
// for forward compatibility.
//
// Builtin 是 builtin 领域的 gRPC 服务, 与 REST 侧 /api/v1/ping 对应.
type BuiltinServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedBuiltinServer()
}

// UnimplementedBuiltinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuiltinServer struct{}

func (UnimplementedBuiltinServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBuiltinServer) mustEmbedUnimplementedBuiltinServer() {}
func (UnimplementedBuiltinServer) testEmbeddedByValue()                 {}

// UnsafeBuiltinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuiltinServer will
// result in compilation errors.
type UnsafeBuiltinServer interface {
	mustEmbedUnimplementedBuiltinServer()
}

func RegisterBuiltinServer(s grpc.ServiceRegistrar, srv BuiltinServer) {
	// If the following call panics, it indicates UnimplementedBuiltinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Builtin_ServiceDesc, srv)
}

func _Builtin_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builtin_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Builtin_ServiceDesc is the grpc.ServiceDesc for Builtin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Builtin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builtin.Builtin",
	HandlerType: (*BuiltinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Builtin_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "builtin.proto",
}
